project:
  type: book

book:
  title: "CCDPH Community Profiles"
  subtitle: "Public health insights of places within suburban Cook County"
  cover-image: profiles_cover.png
  author: "CCDPH Epidemiology Unit"
  date: "Last updated 3/13/2025"
  page-navigation: true
  chapters:
    - intro.qmd
    - scc.qmd
    - ccdph.qmd
    - part: districts.qmd
        - muni_alsip.qmd
        - muni_prospect_heights.qmd
    - part: municipalities.qmd
      chapters:
        - muni_alsip.qmd
        - muni_prospect_heights.qmd
    - part: zctas.qmd
  appendices:
    - methodology.qmd
    - references.qmd
    - definitions.qmd
    - acronyms.qmd
    
bibliography: references.bib

format:
  html:
    theme: [journal, "profiles.scss"]
    favicon: "https://cookcountypublichealth.org/wp-content/uploads/2018/12/cropped-favicon-32x32.png"
    include-in-header: "header.html"
    cache: false
    anchor-sections: true
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    page-navigation: true
    echo: true
    eval: false
    warning: false
    code-fold: true
    crossref:
      chapters: true
  
editor: source
editor_options: 
  chunk_output_type: console