project:
  type: book

book:
  title: "CCDPH Community Profiles"
  subtitle: "Public health summaries of areas within suburban Cook County"
  cover-image: profiles_cover.png
  author: "CCDPH Epidemiology Unit"
  date: "Last updated 1/13/2025"
  page-navigation: true # true by default (adds previous/next page at bottom of page)
  chapters:
    - index.qmd
    - intro.qmd
    - methodology.qmd
    - part: municipalities.qmd
      chapters:
        - alsip.qmd
        - prospect_heights.qmd
  appendices:
    - references.qmd
    - definitions.qmd

bibliography: references.bib

format:
  html:
    theme: [journal, "profiles.scss"]
    favicon: "https://cookcountypublichealth.org/wp-content/uploads/2018/12/cropped-favicon-32x32.png"
    include-in-header: "header.html"
    # cache: false
    # anchor-sections: true
    # smooth-scroll: true
    # link-external-icon: true
    # link-external-newwindow: true
    # page-navigation: true
    # echo: true
    # eval: false
    # warning: false
    # code-fold: true
    # crossref:
    #   chapters: true
  
editor: source
editor_options: 
  chunk_output_type: console