# Index {.unnumbered}

## Welcome
Welcome to the [Cook County Department of Public Health (CCDPH)](https://cookcountypublichealth.org/) Epidemiology Unit employee handbook. This is a dynamic document written, edited, continually enhanced and updated by unit staff employees with secondary contributions from units and institutions both within and outside CCDPH.

## Purpose
The purpose of this document is to provide a centralized source of fundamental information relevant to the Epidemiology Unit including, but not limited to, unit staff, onboarding and offboarding checklists, standard procedures concerning project and data management (e.g., data collection, analysis, and dissemination), document templates, and links to official forms, and many other fun and extremely exciting resources.

As the Unit's primary reference, the handbook aims to ease the discovery of institutional knowledge, thereby reducing frustration associated with browsing otherwise unwieldy directories and files.

## Contribute
The Epidemiology Unit enthusiastically welcomes contributions to this document on a regular basis. If you feel something is missing, confusing, or could otherwise be improved in the handbook, please help fill in the gaps. The document is stored in a private, CCDPH GitHub repository, which eases the group authoring process.

*Explore, learn, and contribute!*